# Generated by Django 4.2.3 on 2023-07-30 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Urls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_name', models.CharField(max_length=100, unique=True)),
                ('pages', models.CharField(max_length=50)),
                ('urls', models.JSONField(default=dict)),
                ('video_name', models.CharField(max_length=100)),
            ],
        ),
    ]
